### ISSUE TITLE
Shaded look and feel for both code types

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#12]
A quick examples with code typeset pandoc-style (ie three backtick r) looks different from knitr-typeset and eval'ed R.  Can we make both look the same?

**Comment by coatless** [comment]
Mmm... Good question. Theoretically, they should be using the same styling. I'll look into the `.tex` preamble being kept.

**Comment by eddelbuettel** [comment]
I am confused too as `knitr` should do this, and I can't see where it would be told not to.

**Comment by eddelbuettel** [comment]
Found it.  We were overriding some basic knitr functionality to make it more sweave-ish.
