### ISSUE TITLE
How would this be used?

### ISSUE THREAD

**Issue by BioDocPete** [eddelbuettel/pinp#19]
Formatting before sending out for review?  
Formatting of the final version for posting the version that the journal does not own?

**Comment by eddelbuettel** [comment]
These questions for _your_ workflow with your submission seem a little orthogonal to us "merely" providing a helpful template.

I had papers in the past where the draft was done with such RMarkdown templates.  You get a LaTeX document as an intermediary output.  Fine-tuning to editor and journal specifications is than possible from the LaTeX document.
