### ISSUE TITLE
Citations not working

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#2]
This doesn't currently work from Markdown.

It still works at the latex layer.

**Comment by coatless** [comment]
Odd, I have the _reverse_ happening. 

e.g. switching: 

```
\cite{10.7287/peerj.preprints.3188v1}
```

to:

```
@10.7287/peerj.preprints.3188v1
```

worked. So, the citations within the `References {#references .unnumbered}` that used RMarkdown style worked.

**Comment by eddelbuettel** [comment]
Yes. 

Resolving `@foo87` pandoc is not an issue.  All rticles styles do that by relying on pandoc.

Only rjournal seems to use latex. but I just tried to carry its code over and couldn't make it work.  It has the extra dance from having to switch to `RJournal.tex` (the outer wrapper).  I could not successfully invoke `tools::texi2pdf()`.   (And we were missing the `Schunk` env, but that trivial.)  

Anyway, don't have time now so that will have to rest.  No working natbib support from Rmd as it stands.
