### ISSUE TITLE
Failed to compile if non-english characters included

### ISSUE THREAD

**Issue by ghost** [eddelbuettel/pinp#20]
What should I change to create a document in a language other than English?
Thank you.

**Comment by eddelbuettel** [comment]
I would suggest the following:

- Look at any other RMarkdown document that does it
- Carry the change over.

I guess that you probably just need to declare a UTF-8 encoding, possibly via `%\VignetteEncoding{UTF-8}` in the vignette header.

**Comment by eddelbuettel** [comment]
There is nothing you need to do.  Quick loG:

```sh
edd@brad:/tmp$ mkdir other-languages
edd@brad:/tmp$ cd other-languages/
edd@brad:/tmp/other-languages$ Rscript -e 'rmarkdown::draft("quickCheck.Rmd", template="pdf", package="pinp", edit=FALSE)'
edd@brad:/tmp/other-languages$ # edits quickCheck.Rmd
edd@brad:/tmp/other-languages$ Rscript -e 'rmarkdown::render("quickCheck.Rmd")'


processing file: quickCheck.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: quickCheck.knit.md

/usr/bin/pandoc +RTS -K512m -RTS quickCheck.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output quickCheck.tex --template /usr/local/lib/R/site-library/pinp/rmarkdown/templates/pdf/resources/template.tex --highlight-style tango --latex-engine pdflatex --natbib 
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.

Output created: quickCheck.pdf
edd@brad:/tmp/other-languages$ 
```

using the following near-minimal (?) RMarkdown input file:

```r
---
title: A Quick Test

author:
  - name: First Author
    affiliation: a
address:
  - code: a
    address: Institute of Smoke and Magic, University of Sometown, Sometown, XY, 12345

keywords:
  - one
  - two

output: pinp::pinp
---

## Introduction 

Il fait chaud en été à Paris.

Schöne Grüße.
```

and it just works as is.

**Comment by ghost** [comment]
Your example with French works indeed. However, If you use _Ελληνικά_ (Greek), you will get an error.

**Comment by eddelbuettel** [comment]
I very strongly suspect that if you do whatever you need to do to typset Greek (or other) letters via Markdown and then LaTeX, it will just work.  We this in the `template.tex` file:

```tex
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
```

which means UTF-8 character should be supported.  For the rest, _i,e.,_ direct input of non latin-1 characters you may need to research how RMarkdown does.  There is no fundamental reason why this can't work.

**Comment by eddelbuettel** [comment]
This [tex.stackexchange.com post](https://tex.stackexchange.com/questions/377613/solve-unicode-char-is-not-set-up-for-use-with-latex-without-special-handling-o) seems relevant.  It may after all we a regular LaTeX issue.  But we're not taking any features away...
