### ISSUE TITLE
Provide pinp.cls if not present

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#23]
I am a little non-plus'ed that adding pinp as the vignette driver leads to two extra files.   

I already figured out how to get rid of one---we can just include the content of the Bibtex-rendered .blg file directly in the source Rmd, which frees us from adding a `foo.bib` file.  Down one.  (Of course, you want it while you still edit the document.  Once done, and included as a more static vignette you do not and the extra file is line noise.)

And I realized that we have a _code hook_ to just copy in `pinp.cls` from the pinp skeleton directory if it is not present in the current working directory---and _tada_ we also get rid of `pinp.cls`.   

Good idea?  Methinks it is.

**Comment by coatless** [comment]
Yeah, I was actually toying around with this in: coatless/uiucthemes#4

Basically, the `pinp` function can call `system.file()` and create the appropriate linking path. Though, I think some of my earlier tests ran afoul with Windows and spaces in the `Program Files` path. I'll need to set up a parallel session to test now as the windows box is fried...

**Comment by eddelbuettel** [comment]
It is trivial, and I will commit it:

```r
    if (!file.exists("pinp.cls"))
        file.copy(system.file("rmarkdown", "templates", "pdf", "skeleton", "pinp.cls",
                              package="pinp"),
                  ".")
```

Has the advantage of copyinig a current `pinp.cls` in too (if you do a quick `rm` pre-rendering) when you are making changes.
