### ISSUE TITLE
Default to two-column, two-side, 9pt

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#25]
In hindsight I think #7 got the defaults wrong.

If nothing is set, we should do 9pt, two-columns, two-sides.

If someone set `one-colum: true`, they get it.  Ditto for `one-sided: true`,

**Comment by coatless** [comment]
Okay, I'll tweak it.

**Comment by eddelbuettel** [comment]
Don't worry I am on it and have it almost ready.
