### ISSUE TITLE
Rewrite skeleton.Rmd

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#3]
Goals of this ticket:

1. [ ] Rewrite skeleton.Rmd with emphasize on removing PNAS specific language. For additional help, add references to `rticles::pnas_article`
2. [ ] Add a markdown example for two-column figure using LaTeX's `figure*` environment
~~3. [ ] Add table example using `knitr::kable()`, c.f. https://github.com/yihui/knitr/issues/1221. Unfortunately, [pandoc is hardcoded to use `longtable`](https://groups.google.com/forum/#!msg/pandoc-discuss/znkTLPkekOg/KH6SplLXi7gJ). Only way to get around this is to [use a python filter](https://github.com/jgm/pandoc/issues/1023). (We weren't fans of this approach...)~~

This has been broken off from issue #1 and elaborated upon.

**Comment by eddelbuettel** [comment]
For tint, I mostly left it as is.  That has some value -- original documentation.   We clearly need an opening prefix and list where we depart
- simpler front page
- LaTeX natbib citation and author-year format
- ....
- Profit!

**Comment by coatless** [comment]
I would like to remove the following sections as I feel like they are too PNAS-specific.



- Reminder.
- Submitting Manuscripts
- Manuscript Length
- Data Archival
- Language-Editing Services
- Supporting Information

<img width="841" alt="screen shot 2017-09-07 at 8 40 39 pm" src="https://user-images.githubusercontent.com/833642/30192363-e1652f64-940c-11e7-8bd3-d08f9ce38c70.png">

**Comment by eddelbuettel** [comment]
That's a very good start, and very well argued graphically :)

**Comment by eddelbuettel** [comment]
We can also of course remove 'Alice and Bob' and this isn't a comp sci class.  Dirk and James, or James and Dirk, will do nicely too.
