### ISSUE TITLE
Condition final line item macros based on YAML

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#36]
Condition these final three lines:

- Show Acknowledgements
- Show Materials
- Show references

c.f.

https://github.com/eddelbuettel/pinp/blob/b6bf4c99d0d94372ec0d51c68b7198c15e18a533/inst/rmarkdown/templates/pdf/resources/template.tex#L74-L76

The hope here is these will address the fragile state of the floats...

**Comment by eddelbuettel** [comment]
We may actually just kill `showmatmethods` which we don't support in the header.

Another one that would be nice is to not auto-insert the bibliography so that when a user is in a fight with latex over floats, it may give a chance to do bibliographies manually.
