### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#40]
Create a unit test based off of what exists in RStudio's rticles package.

c.f.

https://github.com/rstudio/rticles/blob/865247673577cab956a2c87dd1a6b3f1f63cd3aa/tests/testthat/test_formats.R

**Comment by eddelbuettel** [comment]
Suggest to keep it simpler as we are not looping over formats -- so let's just set up a file in `tests/` and `stop()` if not output is produced.   

I would also suggest to not do that at Travis (and maybe not at CRAN either) as life is generally too short (at my timescale) to bother with latex installations.

**Comment by eddelbuettel** [comment]
Actually ... we don't even need that.  Building a tar.gz builds the vignette.  So there.

**Comment by coatless** [comment]
Heh. Gotta love R's packaging system...
