### ISSUE TITLE
Endless loop for some input files

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#44]
Using the current Rcpp vignettes, I am seeing some misbehaved latex runs on eg Rcpp-package. 

I am not yet sure what causes this.

*Edit:* The `\pnasbreak` appears to be involved.

*Edit 2:* Two of the vignettes need a manual `\pnasbreak` at end with pinp 0.0.3.

**Comment by coatless** [comment]
https://github.com/RcppCore/Rcpp/commit/b3fa43ca3202b8d6f2594ecb89d2bc3e7a3df868

So, this revision has the infinite loop?

**Comment by eddelbuettel** [comment]
Well, no, it has the fix.  

Or "workaround" if you wish.  Without the added line, these two vignettes fail under pinp 0.0.3.

**Comment by eddelbuettel** [comment]
Per email discussions with KH, shall we add a new toggle?

**Comment by coatless** [comment]
I think that's the best way forward right now. Would you like me to add it? Or did you add it en-route to work?

**Comment by eddelbuettel** [comment]
I won't be able to get to it for a bit so if you could I'd appreciate it.  We should probably add a silly repo (or subdirectory) with the 10+ Rmd files we have to test with/without the proposed toggle.

**Comment by eddelbuettel** [comment]
Addressed via #47
