### ISSUE TITLE
Tag `pinp` releases

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#48]
We probably should tag the [releases on GitHub](https://github.com/eddelbuettel/pinp/releases). 

v0.0.1 - v0.0.3 will need to be done via CLI

```bash
git tag -a <tag> <commit-hash>
git push origin --tags
```

(FYI: releases are MIA on `tint` and `linl`)

**Comment by eddelbuettel** [comment]
Maybe, maybe not. I do it for Rcpp and one or two other releases, I don't care for many of the other micropackages.

I doubt anybody comes here to fetch historic release 0.0.2.  So a firm _meh_ from me.

**Comment by coatless** [comment]
Tagged for posterity sake.

**Comment by eddelbuettel** [comment]
FWIW: I was (moderately) against it, and am still against.

If you have free time and spare energy, maybe add missing features?
