### ISSUE TITLE
Enabling Extra PNAS features in the YAML section

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#5]
This issue ticket will be resolved when:

- [x] Write the following features alongside fallbacks into the `template.tex` file so they can be set with `yml`: 
    1. [x] Allow for watermarking the document with `true` or `false` (default)
    1. [x] Enabling the doi entry key field and CRAN package URL
    1. [x] Provide footers for the left and right side of the document, where users can add their package or other details.

This has been split off from issue #1

**Comment by coatless** [comment]
So, I'm going to try to enable watermarking later today. The whole... 

```latex
\newboolean{displaywatermark}
\setboolean{displaywatermark}{false} % modify this line
```

in the `.cls` is hogwash as you should be able to use the `printwatermark` interface in the `xwatermark` package.

**Comment by eddelbuettel** [comment]
Ok.  

I struggled with one (relatively simple ?) thing relative to the doi field:  declare a string in the yaml metadata, pass it down, make it part of something typeset.  So instead of allowing the whole doi url (or a free form url) I can only pass down a short string for the package name.  That works -- but a url somehow broke something.  Probably needs more escaping.

**Comment by eddelbuettel** [comment]
In general, there are a bunch a booleans declared in a few places in the latex class file and/or template.tex.  Would be good to clean those up "eventually" when we have a better feel.

I think I settled on what I want to do for a default font (carry over the one used in the current Rcpp vignettes, looks sharper) and coloring (by picking the very blue from the new R logo).  PR for that probably tomorrow.

**Comment by coatless** [comment]
For a font, how about [Roboto](http://www.tug.dk/FontCatalogue/roboto/)? Or [Source Sans Pro](http://www.tug.dk/FontCatalogue/sourcesanspro/)?

**Comment by eddelbuettel** [comment]
See [here](https://github.com/RcppCore/Rcpp/blob/bbd670b54e861db04789b7b3d0b3b88140942bf1/vignettes/Rcpp-attributes.Rnw#L25-L28) and various arguments in favour of microtype as eg [this](http://web.willbenton.com/writing/2008/better-latex) or [this](https://jonasdevlieghere.com/latex-packages-i-wish-i-knew/).

Of the three lines quoted above, we actually only need the third as the others are already "in".

**Comment by coatless** [comment]
I'm sold on the benefits of `microtype`.

Regarding the DOI url, `pandoc` process URL strings in YAML in a unique way c.f. [multiple e-mail generation](https://stackoverflow.com/questions/41706614/pandoc-template-expands-embedded-e-mail-multiple-times). In particular, when a URL is supplied, `pandoc` automatically puts it in the correct "URL-form"... So, with:

```
\doi{\url{$doi$}}
```

This would generate in LaTeX:

```
\doi{\url{\url{doi-value}}
```

Causing latex to explode...

Switching it to:

```
\doi{$doi$}
```

Yields the desired response.

**Comment by eddelbuettel** [comment]
Sweet.  [ And after looking at commits ]  Looks good.
