### ISSUE TITLE
Adjusting abstract font size

### ISSUE THREAD

**Issue by jsta** [eddelbuettel/pinp#50]
I am having trouble finding where I can adjust the abstract font size. Is this possible?

**Comment by eddelbuettel** [comment]
Not as an explicit feature.  What I sometimes do with these markdown wrappers to latex is that I copy out a certain aspect into a local `header.tex` which gets included from the header.  That is a common approach you see used and documented.  Good enough?

**Comment by eddelbuettel** [comment]
Thanks for your understanding.  Also, regular "warning" that the PNAS style seems very finicky about placement of content in two-column mode.  Unless the page is full with "just" the right amount of content we have seen paragraphs get swallowed.  Not something `pinp` can control.  Seems to come with the pnas style terrirotory...

**Comment by jsta** [comment]
I found what I was looking for by adjusting the definition of [`\absfont`](https://github.com/eddelbuettel/pinp/blob/master/inst/rmarkdown/templates/pdf/skeleton/pinp.cls#L169)
