### ISSUE TITLE
Supporting other paper sizes

### ISSUE THREAD

**Issue by saghirb** [eddelbuettel/pinp#57]
File `pinp.cls` originally defined the settings for letter paper size but part of these were moved as part of [issue #24] to `template.tex` to support a4 paper size. [Pull request #55] moved the remaining settings to `template.tex` to accommodate other paper sizes. This changed the hard-coded PNAS settings for letter paper size to relative ones (not particularly desirable).

The current version of `pinp` package supports letter and a4 paper sizes. Is this enough? Should we support other paper sizes? If so, should we keep letter paper settings as per PNAS and make the rest relative where the preference would be to try to get it working in `pinp.cls`?

**Comment by eddelbuettel** [comment]
Yes it is enough, until actually hear from someone using different paper.  So no we do not want other paper sizes.  There is a benefit to _minimal_ changes.

**Comment by saghirb** [comment]
I wanted to use this layout for a5 paper size but this is easily resolved using some pdf command lines tools to create a5 size from a4 (with a font size adjustment). Agree with the minimal change approach :+1:

**Comment by eddelbuettel** [comment]
Good one.  Did the same many moons ago when I still lived over in a3/a4/a5 land :)
