### ISSUE TITLE
change page numbering

### ISSUE THREAD

**Issue by ikashnitsky** [eddelbuettel/pinp#60]
Is it possible to give a custom range of page numbers to a document?
[I have a semi crazy idea to layout PhD thesis as a journal issue using `pinp`]

**Comment by eddelbuettel** [comment]
"Probably" in the sense of "everything is possible with LaTeX".  See eg https://tex.stackexchange.com/questions/66562/how-to-set-page-counter-by-skipping-first-page

Now, is that something pinp needs to expose via its API?  Hm.  Not so sure...  Can you work with a local copy?

**Comment by ikashnitsky** [comment]
Thanks a lot!

Isn't this something that might be generally useful as a yaml option?

**Comment by eddelbuettel** [comment]
Yes that is where we would put it (and where you can put it). I just do not think it is of enough general interest to warrant it as a package feature.  Which is why I would prefer to close this.

**Comment by ikashnitsky** [comment]
Ok, I see. Thank you!

**Comment by eddelbuettel** [comment]
Actually, I think you can even set that in the middle of (or beginning of) your document.  No need for YAML header, and no need for modifications!

**Comment by ikashnitsky** [comment]
@eddelbuettel thanks a lot for pointing me to `\setcounter{page}{N}` -- this is a really easy and elegant solution to my question. 

May I ask another one here. Is there a way to suppress date in the footer and the line "This version was compiled on ..."?

**Comment by coatless** [comment]
Potentially, you could supply a `\date` entry in `include-after:` YAML key that would override the hard coded value used here:

https://github.com/eddelbuettel/pinp/blob/63398731a5ad55799b96420c36b768ee03f27047/inst/rmarkdown/templates/pdf/resources/template.tex#L64
