### ISSUE TITLE
Feature request: pnas_type

### ISSUE THREAD

**Issue by 2005m** [eddelbuettel/pinp#67]
Hi,

In the package rticles, there is an option called pnas_type : pnasinvited which produces a slightly different output than the default pnasresearcharticle. 

Would it please be possible to add this option?

Thank you
Best regards

**Comment by eddelbuettel** [comment]
Could you pretty please preare an example?  I vaguely recall having looked at the very beginning and concluded that some changes that I made to `template.tex` and/or other files would break something.

I could be wrong. Worth trying.  Do you want to take a stab to get the ball rolling?

**Comment by 2005m** [comment]
An example can be created using the following steps in Rstudio:
-File>New File>R Markdown
-In from template select PNAS Journal Article {rticles}
-Change the line 54 from pnas_type: pnasresearcharticle to pnas_type: pnasinvited

I will check tonight whether I can implemented in your package although my latex skills are not great.

Thanks

**Comment by eddelbuettel** [comment]
No, that's great as a first pass. 

Now that you have a modified template, can you which (if any) of the various /options/ still work? I think we may need to do some postprocessing of the (unaltered) PNAS file.

Let's figure out the "what".  We deal with the "next" thereafter.

**Comment by 2005m** [comment]
Yes you can switch to pnasmathematics (which is a one column layout) instead of pnasinvited. 

In your pinp.cls file I think you define the type to use (pnasresearcharticle) on lign 561.

**Comment by eddelbuettel** [comment]
Closing this for lack of follow-up.  So the package will remain focused on the default style.
