### ISSUE TITLE
internationalisation

### ISSUE THREAD

**Issue by tormodb** [eddelbuettel/pinp#68]
Hi, thanks for a great package! 

I was wondering if you have any plans for supporting internationalisation, either by allowing to set this through babel or another comment? It would be great if dates could be formatted according to different languages and contexts.

**Comment by eddelbuettel** [comment]
That should be possible.  Easiest may be to just pass a date through -- after all we _know_ we are coming from R so we have a richer framework than a pure (La)TeX solution. 

Do you want to try that?

**Comment by tormodb** [comment]
Sure, I am probably overcomplicating things.. You are of course right!

**Comment by eddelbuettel** [comment]
Maybe :)

Try assigning to `date_subtitle` in the YAML and see what happens.  That may do.

**Comment by eddelbuettel** [comment]
Dates are now fully customizable via two fields thanks to @ikashnitsky so closing this.
