### ISSUE TITLE
Empty space when not including abstract and keywords

### ISSUE THREAD

**Issue by anguyen1210** [eddelbuettel/pinp#69]
I'm trying to use the template where I do not include any abstract and keyword information, and without any text here, there are still 2-3 lines of empty space before the first lines of text in the body of the document starts in column 1.  I've been trying to figure out how to get ride of this space so the text in both columns start evenly and so that this space disappears.  I'm sure this is an easy fix, but I'm pretty new to working with tex, and I'm stumped.  Haven't found anything online in the usual places, I'm hoping someone here might have ideas.  Thanks!

**Comment by eddelbuettel** [comment]
Did you find anything?

This is not obvious as the PNAS layout is somewhat opinionated.  We override some values, but changing this may be trickier.

**Comment by anguyen1210** [comment]
No, I never figured out a solution, but in the end, I just followed the template and added a short summary to fill the space and keep everything looking nice.  The template is great in any case, thanks!

**Comment by eddelbuettel** [comment]
(I missed a 'not' in my first comment, now added.)

Agreed.  Best to follow the template as there does not seem to be an alternate.  And summaries are good :)
