### ISSUE TITLE
Feature: Provide Support for 1-column version

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#7]
The goal of this ticket is to enable support for a 1-column version.

- [x] To enable 1-column support, see [`rticles::pnas_article()`](https://github.com/rstudio/rticles/blob/93ddb6b53db72e3cb8b29aa77c81c089551fc62b/inst/rmarkdown/templates/pnas_article/resources/template.tex#L76).

This issue has been split off of #1.

**Comment by eddelbuettel** [comment]
Just played with one-column, one-side, different pt side from the intermediate LaTeX file and ... *it all works*!

So maybe make these toggles (one vs two column, one vs two side, 9pt vs 10pt vs 11pt vs 12pt) accessible from YAML?

**Comment by eddelbuettel** [comment]
Now merged from #21
