### ISSUE TITLE
Full abstract in the references

### ISSUE THREAD

**Issue by CosmeSanchezMiguel** [eddelbuettel/pinp#70]
Is there possible to include the abstract of the citations in the references section of pinp?

**Comment by eddelbuettel** [comment]
"Possibly". These things are governed by the bst (== Bibtex style) files. You would have to modify the existing one.

**Comment by eddelbuettel** [comment]
Here is an answer from tex.stackexchange.com pointing to `abstract.bst`:  https://tex.stackexchange.com/questions/64822/how-can-include-the-full-abstract-of-a-citation-in-the-references-section-using

**Comment by eddelbuettel** [comment]
Closing now as both a little stale, and out of scope.

**Comment by eddelbuettel** [comment]
Actually closing now.
