### ISSUE TITLE
inherit from bookdown

### ISSUE THREAD

**Issue by Courvoisier13** [eddelbuettel/pinp#71]
Hi,

thank you for this excellent template!

Is there a way I can make it inherit from bookdown instead of the classic Rmarkdown pdf? Rmarkdown cannot reference sections in the documents using @ref, but bookdown does this correctly

thanks

**Comment by eddelbuettel** [comment]
We follow the latex sttandard and use bibtex via `\cite{}`, `\citep{]`, `\citet{}` and so on.  That is a deliberate choice.  See some of the vignettes using `pinp` for how.   This is unlikely to change, so I suggest we close this.

We also do not impose any outer wrapper.  I mostly just call `rmarkdown::render("myfile.Rmd")`.

**Comment by Courvoisier13** [comment]
Thanks,
I just realized there is no need. The \ref{} for figures and tables defined in chunks work well as do those of sections. I think the new pandoc V 2 addressed a previous issue that needed a workaround.
