### ISSUE TITLE
include-after option

### ISSUE THREAD

**Issue by Courvoisier13** [eddelbuettel/pinp#73]
Hi,

The include-after is missing a \input{} from the template.tex. The code 
```
$for(include-after)$
$include-after$
$endfor$
```
is correctly placed after the bibliography but if we want to include a .tex file, it needs to have a `\input{include-after}`. Otherwise if we put `include-after: somefile.tex` in the yaml, then just the words "somefile.tex" will apprear in the .tex.

Putting `\input{somefile.tex}` in the yaml allows for a workaround. but it's nicer to just put the .tex in the yaml header

**Comment by eddelbuettel** [comment]
They exist here:

https://github.com/eddelbuettel/pinp/blob/01a98d33c427c1dac1f7cb7487b4b8a00bd1fe16/inst/rmarkdown/templates/pdf/resources/template.tex#L129-L131

**Comment by Courvoisier13** [comment]
yes, what i'm saying is that this should be:

```
 $for(include-after)$ 
 $\include{include-after}$
 $endfor$ 
```

**Comment by eddelbuettel** [comment]
Look at the other include:

```
$for(header-includes)$
$header-includes$
$endfor$
```

It does the same.  It is full textual substituion.
