### ISSUE TITLE
Preserve non-fancy quotes in code chunks

### ISSUE THREAD

**Issue by riccardoporreca** [eddelbuettel/pinp#75]
Using `output: pinp::pinp`, the quotes in the code chunks are converted to _fancy_ quotes.

I quickly constructed a minimal example as follows
```rmd
---
title: "Test pinp quotes"
output: pinp::pinp
---

Pinp's quotes in regular text: "dquoted", 'squoted', \`bquoted\`.

Pinp's quotes in inline verbatim text: `"dquoted"`, `'squoted'`.

```r
"dquoted"
'squoted'
`bquoted`
#' Xyz's "dquoted" 'squoted' `bquoted`
```

(I did not find a nice way to render the closing ``` of the code chunk)

This results in 
![image](https://user-images.githubusercontent.com/13663564/61582843-263fb500-ab30-11e9-9bd9-89190cf3e27e.png)

Not sure if this is a desired behavior (I noticed it for the Rcpp vignettes), but in case I tried a quick fix by using LaTeX package [upquote](https://ctan.org/pkg/upquote?lang=en). In particular, adding
```latex
\RequirePackage{upquote} % For keeping actual quotes in verbatim
```
to the class definition [pinp.cls](https://github.com/eddelbuettel/pinp/blob/master/inst/rmarkdown/templates/pdf/skeleton/pinp.cls) seemed to indeed help:
![image](https://user-images.githubusercontent.com/13663564/61582823-fc868e00-ab2f-11e9-8ed5-ed45f084d97a.png)

My LaTeX skills are a bit rusty, so maybe there are more convenient / appropriate ways to achieve the same.

**Comment by eddelbuettel** [comment]
Nice catch.  I may be a little dense but the desired effect is just for the verbatim chunk, correct?  Inline does not seem to change. Or am I missing something?

**Comment by riccardoporreca** [comment]
> the desired effect is just for the verbatim chunk, correct? Inline does not seem to change. Or am I missing something?

From what I see it doesn't seem to affect anything inline (even verbatim inline which was already OK), since inline stuff do not use any of the verbatim-related LaTeX affected by `upquote`, see the generated LaTeX code:
```latex
Pinp's quotes in regular text: ``dquoted'', `squoted', `bquoted`.

Pinp's quotes in inline verbatim text: \texttt{"dquoted"},
\texttt{\textquotesingle{}squoted\textquotesingle{}}.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{"dquoted"}
\StringTok{'squoted'}
\StringTok{`}\DataTypeTok{bquoted}\StringTok{`}
\CommentTok{#' Xyz's "dquoted" 'squoted' `bquoted`}
\end{Highlighting}
\end{Shaded}
```
(I have updated the example with something a little more accurate / sensible)

**Comment by eddelbuettel** [comment]
Ok, I just tossed that in with a simple commit.  Thanks again for the suggestion!

**Comment by riccardoporreca** [comment]
Cool, I will be trying it out very soon while drafting a review of the Rcpp-modules vignette as discussed in https://github.com/RcppCore/Rcpp/issues/976#issuecomment-512543279.
