### ISSUE TITLE
Failed to compile the provided template

### ISSUE THREAD

**Issue by sahirbhatnagar** [eddelbuettel/pinp#76]
I'm getting the exact same error as shown here (Last updated on 2019-08-29 02:49:05 CEST):
http://cran.utstat.utoronto.ca/web/checks/check_results_Rcpp.html

I tried reinstalling my TeXLive distribution on Ubuntu using `tinytex` but that didn't work. I'm not really sure how to provide a reproducible example with a reproducible environment for this issue.

**Comment by eddelbuettel** [comment]
I work on Ubuntu (and Debian) and have for a decade (and almost 2 1/2) . (On both `tinytex` does not work for me, was never needed, and just gets in the way.  I wish `rmarkdown` and `knitr` allowed to not have it.).  

And as author of `pinp` it obviously works for me.   You are probably "just" lacking some of the in-distro packages of texlive.  I recommend studying the error message for 'missing file' messages and going to packages.ubuntu.com to search for which package has them.

**Comment by eddelbuettel** [comment]
As a shortcut, it looks like `pgf` is missing and I seem to have that from `texlive-pictures`:

```
edd@rob:~$ grep -l  "/pgf/" /var/lib/dpkg/info/texlive-*list
/var/lib/dpkg/info/texlive-pictures-doc.list
/var/lib/dpkg/info/texlive-pictures.list
edd@rob:~$
```

**Comment by sahirbhatnagar** [comment]
Ok thanks for the quick reply. I got it to work. For those that might encounter the same problem these are the steps I took to fix it:

1. Uninstall `tinytex` with `tinytex::uninstall_tinytex()`
2. Delete `texlive`
3. Re-install `texlive` using `aptitude`: `aptitude install texlive-full`
4. Install `texlive-science`: `aptitude install texlive-science`

**Comment by eddelbuettel** [comment]
Nice.  I'll close this then.

I think `tinytex`, while useless to you and me, will still creep back in as a Depends of `rmarkdown` or `knitr`.
