### ISSUE TITLE
pinp breaking under current texlive

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#77]
KH writes in private email.  Has not bitten me yet on Ubuntu...

> Pls see
<https://cran.r-project.org/web/checks/check_results_pinp.html>:
apparently pinp.cls no longer works with current texlive.
>
> For me problems started with the recent Debian testing upgrade to
texlive 2019.20190830-1; for Brian a few days sooner.
>
> My check logs show tlmgr fail because there is no initialized user
tree.  If I run tlmgr init-usertree, my logs look like Brian's, modulo
mine using TEXMFHOME (as tlmgr on Debian will not use other locations).
>
> The same problems occur with packages
>
>  ChemoSpec ChemoSpec2D RProtoBuf Rcpp RcppArmadillo RcppCNPy
>  RcppClassic RcppGSL RcppZiggurat mistr pinp readJDX
>
>which are exactly the packages using pinp::pinp to produce a pinp
document.
>
> Of course, tikzlibrarytopaths.code.tex is installed on the check
systems.  Nevertheless, knitr asks tinytex to try to install pgf, which
does not help, as compilation still fails with a missing
\begin{document} error in pinp.cls.  I suspect what is going on is that
recent texlive changes have invalidated pinp.cls presumably with an
error in tikzlibrarytopaths.code.tex, knitr incorrectly infers that this
is missing and asks tlmgr to install, and then fails again.
>
> Hard to find out more on my end: can you please have a look?

**Comment by eddelbuettel** [comment]
Follow-up tests and emails point to a regression in CTAN / texlive package `titlesec`.

**Comment by coatless** [comment]
Long story short, we needed to update to the newest `pnas` styling.
