### ISSUE TITLE
support multiple columns via easier pandoc notation

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#87]
Both @coatless and I already know and cherish (given that we talked about it in a different context) that pandoc lets us use multiple columns in a document using `::::::` blocks with inner `:::` blocks.

But only wizard @grantmcdermott knows how to [do it _in general_ or even in _one document over html and pdf_](https://github.com/grantmcdermott/two-col-test) (giving the credit back to @yihui 's book).  

As multi-column is really good for _e.g._ code snippets, I recently "borrowed" the css trick for a html vignette I tried (with a currently less widely-used markdown wrapper) but that hit [the wall at CRAN over pandoc 2.0 lacking on Windoze](https://stat.ethz.ch/pipermail/r-package-devel/2020q3/006051.html) so I converted it to pdf.  Using this package.

Which was lacking the multi-column setup for LaTeX so I copied it into the document header, with an added `\noindent`.  That is useful, so I will add this the package now and plan to let the PR sit there for a day or so.

**Comment by grantmcdermott** [comment]
Late seeing this, but everything LGTM. 

(Quasi-related to the HTML to PDF printing: I have a longer-term goal of building a PNAS template for [pagedown](https://github.com/rstudio/pagedown), but that's in the back of the queue with a bunch of other unrealised ideas!)

**Comment by eddelbuettel** [comment]
Go for it :) 

I consider html rendering to be semi-random and html-to-pdf a fool's errand as I don't trust browsers.  Make pdf files like the man himself intended.  Related:  https://twitter.com/keenanisalive/status/1309826322944978945

Update to `pinp` worked great when the (much) smaller and otherwise nice html vignette framework turned out to be "CRAN incomatible" as Uwe uses a `pandoc.exe` version from the very dark ages.  Pdf has the very strong thing going for it that I can slurp it into a _Sweave_ document and then not depend on _anything_ that may change or break.  And CI runs are quicker as there is not phantom bloat of Depends/Imports/LinkingTo/Suggests as you don't need `rmarkdown` and `knitr`.

Still a shame as the CSS I use for the mini html vignette was awesome for the purpose.  Ah well.
