### ISSUE TITLE
Alternative look and feel: pnasinvited

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#9]
The visual appearance of this is pretty attractive: pnasrticle opting into `pnasinvited` rather than the default of `pnasresearcharticle`.  The header could change, but the rest is pretty decent too.

![image](https://user-images.githubusercontent.com/673121/30240687-b389945c-953a-11e7-8f7d-8210d079046d.png)

**Comment by eddelbuettel** [comment]
There is also unconditional code in this sub-stylefile  to turn on sans serif fonts which we could carry over as an optional toggle in yaml:

```
%% Set sans as default font
\renewcommand{\familydefault}{\sfdefault}
\renewcommand{\keywordsfont}{\sffamily}
```

**Comment by coatless** [comment]
Very nice! How about adding this as `pinp_simplified()`?

**Comment by eddelbuettel** [comment]
Why not just a toggle?  I don't see (yet) why we'd need a second document type for two line of latex code.

**Comment by eddelbuettel** [comment]
I think we can close this.  We now have colours, and we have a spiffier-than-default font.
